few_shots = [
    {
     'Question' : "How many extra small size white color nike t-shirts are left ?",
     'SQLQuery' : "SELECT `stock_quantity` FROM t_shirts WHERE `brand` = 'Nike' AND `size` = 'XS' AND `color` = 'White'",
     'SQLResult': "Result of the SQL query",
     'Answer' : "There are 53 extra small size white color Nike t-shirts left."
    },
    {
     'Question': "How much is the price of the inventory for all small size t-shirts?",
     'SQLQuery':"SELECT SUM(price*stock_quantity) FROM t_shirts WHERE size = 'S'",
     'SQLResult': "Result of the SQL query",
     'Answer': "The total price of the inventory for all small size t-shirts is 21998."
    },
    {
     'Question': "If we have to sell all the Levi's T-shirts today with discounts applied. How much revenue our store will generate (post discounts)?" ,
     'SQLQuery' : """
        select sum(a.total_amount * ((100 - COALESCE(discounts.pct_discount,0))/100)) as total_revenue from
        (select sum(price*stock_quantity) as total_amount, t_shirt_id from t_shirts where brand = 'Levi'
        group by t_shirt_id) a left join discounts on a.t_shirt_id = discounts.t_shirt_id
        """,
     'SQLResult': "Result of the SQL query",
     'Answer': "The total revenue from Levi t-shirts, considering any applicable discounts, is 31526.30."
    } ,
    {
      'Question' : "If we have to sell all the Levi's T-shirts today. How much revenue our store will generate without discount?" ,
      'SQLQuery': "SELECT SUM(price * stock_quantity) FROM t_shirts WHERE brand = 'Levi'",
      'SQLResult': "Result of the SQL query",
      'Answer' : "The total value of Levi t-shirts in stock is 33351."
    },
    {
     'Question': "How many Levi's white color t-shirts of are available?",
     'SQLQuery' : "SELECT sum(stock_quantity) FROM t_shirts WHERE brand = 'Levi' AND color = 'White'",
     'SQLResult': "Result of the SQL query",
     'Answer' : "There are 203 Levi's white color t-shirts available."
    },
    {
     'Question': "How many Adidas T shirts I have left in my store?",
     'SQLQuery' : "SELECT SUM(`stock_quantity`) FROM `t_shirts` where brand='Adidas'",
     'SQLResult': "Result of the SQL query",
     'Answer' : "There are 996 Adidas T-shirts are avilable in the store."
    },
    {
     'Question': "How much revenue our store will generate by selling all Van Heuson TShirts without discount?",
     'SQLQuery' : "SELECT SUM(`price` * `stock_quantity`) FROM `t_shirts` WHERE brand = 'Van Huesen'",
     'SQLResult': "Result of the SQL query",
     'Answer' : "The total revenue generated by selling all Van Heusen T-shirts without discount is 42545."
    }
]